import Head from "next/head";

const PageTemplate = (props) => {
    return (
        <>
            <Head>
                <title>{ props.head.title }</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main
                style={{ 
                    display: "flex",
                    flexDirection: "column",
                    flexGrow: 1
                }}
                >
                { props.children }
            </main>
        </>
    );
}

export default PageTemplate;